@baseurl = http://127.0.0.1:5000

###register a user
POST {{baseurl}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "njorogekimenyu@gmail.com",
    "username": "njoroge",
    "password": "12345678",
    "confirm_password": "12345678"
}

###login a user
POST {{baseurl}}/api/v1/auth/login
Content-Type: application/json

{
    "username": "njoroge",
    "password": "12345678"
}

###testing the route
GET {{baseurl}}/test

###testing creating a product
POST {{baseurl}}/api/vi/products/create
Content-Type: application/json

{
  "name": "Product Name",
  "description": "Product Description",
  "price": 19.99,
  "image": "product.jpg",
  "category": "Electronics",
    "quantity": 10
}
